Repository hanowwl/recruit.hanowl.com, pull requests merged in 2023-03, with the labels that each got.

#2 feat: add supabase client
  .gitignore
  .pnp.cjs
  .vscode/settings.json
  .yarn/cache/@supabase-functions-js-npm-2.1.0-7011a7a115-231addfa49.zip
  .yarn/cache/@supabase-gotrue-js-npm-2.12.2-a967976c09-0ee9203b80.zip
  .yarn/cache/@supabase-postgrest-js-npm-1.4.1-ffc3611e43-0a4ad721a5.zip
  .yarn/cache/@supabase-realtime-js-npm-2.6.0-7e7170aaca-3a3b696a02.zip
  .yarn/cache/@supabase-storage-js-npm-2.3.1-c49de8b7af-b502bc0735.zip
  .yarn/cache/@supabase-supabase-js-npm-2.10.0-5aecca0445-60da311e9a.zip
  .yarn/cache/@types-phoenix-npm-1.5.5-e3a6f2877c-2dfb59c51c.zip
  .yarn/cache/bufferutil-npm-4.0.7-77a45bb7a3-f75aa87e3d.zip
  .yarn/cache/cross-fetch-npm-3.1.5-e414995db9-f6b8c6ee3e.zip
  .yarn/cache/d-npm-1.0.1-64afbbc689-49ca0639c7.zip
  .yarn/cache/debug-npm-2.6.9-7d4cb597dc-d2f51589ca.zip
  .yarn/cache/es5-ext-npm-0.10.62-f20aca46cb-25f42f6068.zip
  .yarn/cache/es6-iterator-npm-2.0.3-4dadb0ccc1-6e48b1c2d9.zip
  .yarn/cache/es6-symbol-npm-3.1.3-34d72f2a23-cd49722c2a.zip
  .yarn/cache/ext-npm-1.7.0-580588ab93-ef481f9ef4.zip
  .yarn/cache/is-typedarray-npm-1.0.0-bbd99de5b6-3508c6cd0a.zip
  .yarn/cache/ms-npm-2.0.0-9e1101a471-0e6a22b8b7.zip
  .yarn/cache/next-tick-npm-1.1.0-e0eb60d6a4-83b5cf3602.zip
  .yarn/cache/node-fetch-npm-2.6.7-777aa2a6df-8d816ffd1e.zip
  .yarn/cache/node-gyp-build-npm-4.6.0-5434aac3e5-25d78c5ef1.zip
  .yarn/cache/tr46-npm-0.0.3-de53018915-726321c5ea.zip
  .yarn/cache/type-npm-1.2.0-e67311c4b2-dae8c64f82.zip
  .yarn/cache/type-npm-2.7.2-626963ea46-0f42379a8a.zip
  .yarn/cache/typedarray-to-buffer-npm-3.1.5-aadc11995e-99c11aaa8f.zip
  .yarn/cache/utf-8-validate-npm-5.0.10-93e9b6f750-5579350a02.zip
  .yarn/cache/webidl-conversions-npm-3.0.1-60310f6a2b-c92a0a6ab9.zip
  .yarn/cache/websocket-npm-1.0.34-3aaa6c5dc0-8a0ce6d79c.zip
  .yarn/cache/whatwg-url-npm-5.0.0-374fb45e60-b8daed4ad3.zip
  .yarn/cache/yaeti-npm-0.0.6-cffd01e35a-6db12c152f.zip
  package.json
  src/constant/env.ts
  src/constant/index.ts
  src/supabase.ts
  src/vite-env.d.ts
  yarn.lock
Labels: ✨ 기능

#8 chore(deps): setup `react-router-dom`
  .pnp.cjs
  .yarn/cache/@remix-run-router-npm-1.3.3-f2831232da-9280f1c3e4.zip
  .yarn/cache/react-router-dom-npm-6.8.2-9aed31c3b9-eddc8b88e2.zip
  .yarn/cache/react-router-npm-6.8.2-48f13a628a-9e98d03e1f.zip
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/main/index.tsx
  yarn.lock
Labels: ✨ 기능

#9 feat(supabase): add supabase database types and github-action
  .eslintignore
  .github/workflows/update-types.yml
  .pnp.cjs
  .prettierignore
  .yarn/cache/bin-links-npm-4.0.1-08882d205f-a806561750.zip
  .yarn/cache/cmd-shim-npm-6.0.1-87ebf774a0-359006b3a5.zip
  .yarn/cache/data-uri-to-buffer-npm-4.0.1-5c66a78beb-0d0790b67f.zip
  .yarn/cache/fetch-blob-npm-3.2.0-28e01becfc-f19bc28a2a.zip
  .yarn/cache/formdata-polyfill-npm-4.0.10-e03013c013-82a34df292.zip
  .yarn/cache/node-domexception-npm-1.0.0-e1e813b76f-ee1d37dd2a.zip
  .yarn/cache/node-fetch-npm-3.3.0-45d971325c-e9936908d2.zip
  .yarn/cache/npm-normalize-package-bin-npm-3.0.0-66c99675c5-6a34886c15.zip
  .yarn/cache/read-cmd-shim-npm-4.0.0-2339b15fb0-2fb5a8a389.zip
  .yarn/cache/supabase-npm-1.41.6-58b6378936-47acd3e110.zip
  .yarn/cache/web-streams-polyfill-npm-3.2.1-835bd3857e-b119c78574.zip
  .yarn/cache/write-file-atomic-npm-5.0.0-2ece8bba61-6ee16b1955.zip
  package.json
  src/types/supabase.ts
  yarn.lock
Labels: ✨ 기능

#13 feat(components): add `Modal` component, and `useModal` custom-hook
  .pnp.cjs
  .yarn/cache/@fortawesome-fontawesome-common-types-npm-6.3.0-eacaac4a37-ece7153919.zip
  .yarn/cache/@fortawesome-fontawesome-svg-core-npm-6.3.0-b7e80baff5-2479d4b0dc.zip
  .yarn/cache/@fortawesome-free-regular-svg-icons-npm-6.3.0-956db3696f-5efc11add7.zip
  .yarn/cache/@fortawesome-free-solid-svg-icons-npm-6.3.0-b7a91b016c-5cffcdb954.zip
  .yarn/cache/@fortawesome-react-fontawesome-npm-0.2.0-a36215138f-f652a0c217.zip
  .yarn/cache/jotai-npm-2.0.3-56839d68a0-3ad1d6a9b7.zip
  package.json
  src/atoms/index.ts
  src/atoms/modal.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styled.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useModal.tsx
  src/main.tsx
  src/pages/main/index.tsx
  yarn.lock
Labels: ✨ 기능

#17 feat: add component structure and default layout
  .pnp.cjs
  .yarn/cache/@emotion-is-prop-valid-npm-0.8.8-261a0f2426-bb7ec6d48c.zip
  .yarn/cache/@emotion-memoize-npm-0.7.4-5648cf11b8-4e3920d4ec.zip
  .yarn/cache/framer-motion-npm-10.1.0-3c813338e6-adeb92f931.zip
  package.json
  src/App.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Footer/styled.ts
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/styled.ts
  src/components/common/index.ts
  src/components/index.ts
  src/components/layouts/DefaultLayout/index.tsx
  src/components/layouts/DefaultLayout/styled.ts
  src/components/layouts/index.ts
  src/constant/index.ts
  src/constant/menu.ts
  yarn.lock
Labels: ✨ 기능, 🎨 디자인

#16 feat(components): add `LoginModalContent` modal component
  src/components/common/Modal/styled.ts
  src/components/modal/LoginModalContent/index.tsx
  src/components/modal/LoginModalContent/styled.ts
  src/components/modal/index.ts
  src/pages/main/index.tsx
Labels: ✨ 기능

#19 fix(components): resolve navbar obscured page content issue
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/styled.ts
  src/components/layouts/DefaultLayout/styled.ts
Labels: 🐛 버그

#24 feat(components): add toast component and hook
  src/atoms/index.ts
  src/atoms/toast.ts
  src/components/common/Toast/index.tsx
  src/components/common/Toast/styled.ts
  src/components/common/index.ts
  src/constant/toast.ts
  src/hooks/index.ts
  src/hooks/useToast.ts
  src/main.tsx
  src/pages/main/index.tsx
Labels: ✨ 기능

#25 feat(section): implements main page schedule section
  src/components/index.ts
  src/components/main/ScheduleSection/index.tsx
  src/components/main/ScheduleSection/styled.ts
  src/components/main/index.ts
  src/constant/schedule.ts
  src/main.tsx
  src/pages/main/index.tsx
Labels: ✨ 기능

#37 chore: update team introduce sections
  src/App.tsx
  src/constant/teams.tsx
  src/pages/teams/index.ts
  src/pages/teams/main/index.tsx
  src/pages/teams/main/styled.ts
Labels: ♻️ 리팩토링, NO CODE REVIEW

#39 feat(pages): add team apply page
  src/App.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/styled.ts
  src/components/common/Modal/index.tsx
  src/components/common/index.ts
  src/graphql/getResumeInput.gql
  src/graphql/resume.gql
  src/pages/teams/apply/index.tsx
  src/pages/teams/apply/styled.ts
  src/pages/teams/index.ts
  src/providers/auth.tsx
  src/supabase.ts
  src/types/supabase.ts
Labels: ✨ 기능, NO CODE REVIEW

#36 feat(pages): implement qna page
  src/App.tsx
  src/components/index.ts
  src/components/qna/QnASection/index.tsx
  src/components/qna/QnASection/styled.ts
  src/components/qna/SelectMenuSection/index.tsx
  src/components/qna/SelectMenuSection/styled.ts
  src/components/qna/index.ts
  src/constant/qnaMenu.ts
  src/pages/index.ts
  src/pages/qna/index.tsx
  src/pages/qna/styled.ts
Labels: ✨ 기능, NO CODE REVIEW

#42 hotfix(providers): resolve a not render page issue when user not authenticated
  src/providers/auth.tsx
Labels: 🐛 버그, NO CODE REVIEW

#43 hotfix(pages): replace buttons in auth page to Button component
  src/components/layouts/AuthLayout/styled.ts
  src/pages/auth/signin/index.tsx
  src/pages/auth/signup/index.tsx
Labels: 🐛 버그, NO CODE REVIEW

#44 fix: add pretendard.css link into index.html
  index.html
  src/constant/teams.tsx
Labels: 🐛 버그, NO CODE REVIEW

#45 fix(components): disable MainSection cricles for mobile support
  src/components/main/MainSection/index.tsx
Labels: 🐛 버그, NO CODE REVIEW

#46 fix: update second grade depertment to new depertments list
  src/pages/auth/signup/index.tsx
Labels: 🐛 버그, NO CODE REVIEW

#47 fix(pages): not update resume when already insert answer
  src/pages/teams/apply/index.tsx
Labels: 🐛 버그, NO CODE REVIEW

#49 refactor: `1.0.0` refactoring and some bug fix
  .eslintrc
  index.html
  src/App.tsx
  src/atoms/modal.ts
  src/atoms/toast.ts
  src/components/common/Button/styled.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/styled.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styled.ts
  src/components/common/Navbar/index.tsx
  src/components/common/Toast/index.tsx
  src/components/index.ts
  src/components/layouts/AuthLayout/index.tsx
  src/components/layouts/DefaultLayout/index.tsx
  src/components/main/MainSection/index.tsx
  src/components/main/ScheduleSection/index.tsx
  src/components/qna/QnASection/index.tsx
  src/components/qna/SelectMenuSection/index.tsx
  src/constant/index.ts
  src/constant/menu.ts
  src/constant/toast.ts
  src/graphql/getResumeInput.gql
  src/graphql/test.gql
  src/hooks/index.ts
  src/hooks/useModal.tsx
  src/hooks/useToast.ts
  src/pages/auth/signup/index.tsx
  src/pages/auth/signup/styled.ts
  src/pages/main/index.tsx
  src/pages/qna/index.tsx
  src/pages/qna/styled.ts
  src/pages/teams/apply/index.tsx
  src/pages/teams/main/styled.ts
  src/providers/auth.tsx
  src/styles/font/index.ts
  src/styles/font/pretendard.ts
  src/styles/global.ts
  src/styles/index.ts
Labels: ♻️ 리팩토링, 🐛 버그

#51 feat(pages): add admin resume list page
  .pnp.cjs
  .yarn/cache/@tanstack-react-table-npm-8.7.9-a8ac610919-3c704ac903.zip
  .yarn/cache/@tanstack-table-core-npm-8.7.9-12d32ed77f-78d2314928.zip
  .yarn/cache/dayjs-npm-1.11.7-d5cd5b2919-5003a7c1dd.zip
  package.json
  src/App.tsx
  src/components/common/Modal/styled.ts
  src/components/common/PrivateRoute/index.tsx
  src/components/common/Table/index.tsx
  src/components/common/Table/styled.ts
  src/components/common/index.ts
  src/constant/menu.ts
  src/constant/teams.tsx
  src/graphql/admin.gql
  src/pages/admin/index.ts
  src/pages/admin/resumes/index.tsx
  src/pages/admin/resumes/table.helper.ts
  src/pages/admin/resumes/types.ts
  yarn.lock
Labels: ✨ 기능, NO CODE REVIEW

#52 Release v1.0.1
  .eslintrc
  .pnp.cjs
  .yarn/cache/@tanstack-react-table-npm-8.7.9-a8ac610919-3c704ac903.zip
  .yarn/cache/@tanstack-table-core-npm-8.7.9-12d32ed77f-78d2314928.zip
  .yarn/cache/dayjs-npm-1.11.7-d5cd5b2919-5003a7c1dd.zip
  index.html
  package.json
  src/App.tsx
  src/atoms/modal.ts
  src/atoms/toast.ts
  src/components/common/Button/styled.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/styled.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styled.ts
  src/components/common/Navbar/index.tsx
  src/components/common/PrivateRoute/index.tsx
  src/components/common/Table/index.tsx
  src/components/common/Table/styled.ts
  src/components/common/Toast/index.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layouts/AuthLayout/index.tsx
  src/components/layouts/DefaultLayout/index.tsx
  src/components/main/MainSection/index.tsx
  src/components/main/ScheduleSection/index.tsx
  src/components/qna/QnASection/index.tsx
  src/components/qna/SelectMenuSection/index.tsx
  src/constant/index.ts
  src/constant/menu.ts
  src/constant/teams.tsx
  src/constant/toast.ts
  src/graphql/admin.gql
  src/graphql/getResumeInput.gql
  src/graphql/test.gql
  src/hooks/index.ts
  src/hooks/useModal.tsx
  src/hooks/useToast.ts
  src/pages/admin/index.ts
  src/pages/admin/resumes/index.tsx
  src/pages/admin/resumes/table.helper.ts
  src/pages/admin/resumes/types.ts
  src/pages/auth/signup/index.tsx
  src/pages/auth/signup/styled.ts
  src/pages/main/index.tsx
  src/pages/qna/index.tsx
  src/pages/qna/styled.ts
  src/pages/teams/apply/index.tsx
  src/pages/teams/main/styled.ts
  src/providers/auth.tsx
  src/styles/font/index.ts
  src/styles/font/pretendard.ts
  src/styles/global.ts
  src/styles/index.ts
  yarn.lock
Labels: 👏🏻 배포, NO CODE REVIEW
